import { Injectable } from '@angular/core';
import { FicheProduit } from '../interface/fiche-produit';

@Injectable({
  providedIn: 'root'
})
export class FicheProduitService {

  constructor() { }

  ficheProduitArray: Array<FicheProduit> = [
    {uuidProduit: "48d0e776-6b3a-4d61-98c1-2fb3028b70a1",
      marque: "Advence",
      modele: "CLA-GTA250",
      taille: "47.2cm x 3.4cm",
      title: "LE CLAVIER GAMING RGB AU RAPPORT QUALITÉ / PRIX IMBATTABLE",
      descriptif1: "L'Advance RGB GTA 250 est un superbe clavier gaming avec des touches rétro-éclairées gravées au laser et faciles à repérer. Il est idéal lorsque vous jouez dans des conditions de faible éclairage ou dans l'obscurité. Il s’illumine avec un rétro-éclairage \"rainbow\" composé de 7 couleurs. Il vous donne le choix entre son mode fixe ou breathing et il vous laisse la possibilité de régler sa luminosité selon plusieurs niveaux. Le rétro-éclairage peut aussi être désactivé si vous le souhaitez.",
      descriptif2 : "Conçu pour vous suivre dans toutes vos sessions gaming intensives, il se présente à vous avec son superbe châssis design en métal robuste, et vous offre une frappe silencieuse particulièrement confortable grâce à ses touches membranes semi-mécaniques. Ses larges patins en caoutchouc lui confèrent une grande stabilité. Atout indispensable à tout gamer, le GTA250 d'Advance offre un confort de jeu optimal avec son mode Play qui vous permet de désactiver la touche Windows. Ainsi, plus aucun risque de quitter votre jeu après une frappe accidentelle.",
      caracteristiques1: "Clavier gaming à touches semi-mécaniques et rétro-éclairage LED RGB",
      caracteristiques2: "AZERTY, Français",
      caracteristiques3: "105 Touches semi-mécaniques",
      caracteristiques4: "Rétro-éclairage",
      caracteristiques5: "Couleurs du rétro-éclairage : Rainbow 7 Couleurs, luminosité réglable, mode breathing",
      caracteristiques6: "Touches raccourcis multimédia : 12",
      caracteristiques7: "Système(s) d'exploitation supporté(s) : Windows XP à Windows 10",
      caracteristiques8: "Interface USB",
      caracteristiques9: "Hauteur réglable : 1 position",
      caracteristiques10: "Longueur du câble : 1.7 m",
      caracteristiques11: "Dimensions (L x l x H) : 47.2 x 18.6 x 3,4 cm",
      caracteristiques12: "Poids : 1.1 Kg"
  },{
    uuidProduit: "efc09587-cc23-4b16-b534-dc1b015a2f0e",
    marque: "Advance",
    modele: "CLA-GTA230",
    taille: "45.4 cm x 3.4 cm",
    title: "UN CLAVIER GAMING RGB PERFORMANT ET ACCESIBLE",
    descriptif1: "L'Advance RGB GTA 230 est un clavier gaming conçu pour que vous puissiez vous dépasser lors de toutes vos sessions gaming intenses. Il est doté de touches rétro-éclairées gravées au laser, faciles à repérer dans des conditions de faible éclairage ou dans l'obscurité. Il s’illumine avec un rétro-éclairage \"rainbow\" composé de 7 couleurs. Il vous donne le choix entre son mode fixe ou breathing et il vous laisse la possibilité de régler sa luminosité selon plusieurs niveaux. Le rétro-éclairage peut aussi être désactivé si vous le souhaitez.",
    descriptif2 : "Idéal lorsque vos jeux montent en intensité, il met à votre disposition une frappe confortable et silencieuse, pour une saisie rapide, grâce à ses touches membranes semi-mécaniques. Ses larges patins en caoutchouc lui confèrent une grande stabilité. Enfin, atout indispensable, il offre un confort de jeu optimal grâce à son mode Play qui vous permet de désactiver la touche Windows. Ainsi, vous ne risquez pas de quitter votre jeu après une frappe accidentelle.",
    caracteristiques1: "Clavier gaming avec rétro-éclairage LED RGB",
    caracteristiques2: "AZERTY, Français",
    caracteristiques3: "105 Touches membranes semi-mécaniques",
    caracteristiques4: "Rétro-éclairage",
    caracteristiques5: "Couleurs du rétro-éclairage : Rainbow 7 Couleurs, luminosité réglable, mode breathing",
    caracteristiques6: "Touches Windows",
    caracteristiques7: "Touches raccourcis multimédia : 12",
    caracteristiques8: "Système(s) d'exploitation supporté(s) : Windows XP à Windows 10",
    caracteristiques9: "Interface USB",
    caracteristiques10: "Hauteur réglable : 1 position",
    caracteristiques11: "Longueur du câble : 1.4 m",
    caracteristiques12: "Coloris : Noir"
  },{
    uuidProduit: "2efb24f6-502b-49b4-884e-1c23c3bb9a26",
    marque: "ASUS",
    modele: "90MP01W0-BKFA00",
    taille: "462 mm x 39 mm",
    title: "Le plus versatile des claviers",
    descriptif1: "Ne laissez aucune chance à vos adversaires avec le ASUS ROG Claymore II. Ce clavier filaire ou sans fil est doté de commutateurs mécaniques optiques rouges ROG RX qui offrent une sensation fluide et linéaire pour vous donner une réponse quasi instantanée au moment où vous appuyez sur la touche. Transformez facilement votre clavier en clavier TKL lors de vos sessions gaming grâce au pavé numérique amovible et placez-le à droite ou à gauche selon vos préférences du moment lorsque vous souhaitez travailler.",
    descriptif2 : "Le ASUS ROG Claymore II embarque des commutateurs mécaniques optiques ROG RX rouges pour une victoire quasi certaine à chaque bataille. En effet, avec un point d'actionnement de 1,5 mm, profitez d'entrées ultra-rapides alors que la force initiale de 40g empêche les frappes accidentelles et va jusqu'à 55g pour un retour de rebord parfait. Votre adversaire n'a alors aucune chance, à chaque pression sur une touche, l'action se fait instantanément.",
    descriptif3: "Le clavier ASUS ROG Claymore II est doté de la technologie Aura Sync RGB qui vous offre la possibilité de personnaliser votre clavier à l'aide d'une grande variété de couleurs et d'effets lumineux. De plus, l'éclairage peut être facilement synchronisé avec les périphériques de l'éco-système Aura afin de créer un environnement unique et affirmer vos préférences. Et grâce à sa conception amovible, détachez facilement le pavé numérique, placez-le à gauche ou à droite. Quant au repose-poignet magnétique amovible, il rend les longues sessions de jeu confortables.",
    caracteristiques1: "Clavier à interrupteurs optiques rouges (switches ASUS ROG RX Red)",
    caracteristiques2: "Point d'actionnement : 1,5 mm",
    caracteristiques3: "Connectivité filaire ou sans fil RF 2.4 GHz",
    caracteristiques4: "Pavé numérique amovible : possibilité de le placer à gauche ou à droite du clavier",
    caracteristiques5: "Repose-poignets magnétique amovible",
    caracteristiques6: "Rétroéclairage Aura Sync RGB",
    caracteristiques7: "Batterie intégrée de 4000 mAh offrant jusqu'à 100 heures d'autonomie en mode sans fil",
    caracteristiques8: "Compatibilité : Windows 10",
    caracteristiques9: "Dimensions : 462 x 155 x 39 mm",
    caracteristiques10: "Poids : 1156 g",
  },{
    uuidProduit: "725de77e-9d9b-4e1c-b1c4-5824b4f618c5",
    marque: "ASUSASUS",
    modele: "90MP03EC-BKFA10",
    taille: "306 mm x 26.5 mm",
    title: "Compact et élégant pour briller en jeu",
    descriptif1: "Facilitez-vous la victoire grâce au clavier ASUS ROG Falchion RX Low Profile. Avec son format compact, seulement 65% d'un clavier traditionnel, il dit adieu au surplus des autres claviers en gardant uniquement l'essentiel pour vous permettre de remporter de nombreuses batailles. Il est doté de commutateurs mécaniques (switches ASUS ROG RX Low Profile) qui offrent des frappes tactiles précises. L'ASUS ROG Falchion RX Low Profile possède également un couvercle de protection pour un transport en toute sécurité.",
    caracteristiques1: "Clavier mécanique ultra-compact 65% (AZERTY, Français)",
    caracteristiques2: "Switches ASUS ROG RX Low Profile",
    caracteristiques3: "100% anti-ghosting et N-Key Rollover",
    caracteristiques4: "Connectivité filaire USB et sans fil Bluetooth 5.1 et RF 2.4 GHz",
    caracteristiques5: "Taux d'interrogation : 1000 Hz",
    caracteristiques6: "Enregistrement de macros à la volée",
    caracteristiques7: "Mémoire embarquée : jusqu'à 6 profils",
    caracteristiques8: "Rétroéclairage Aura Sync RGB par touche",
    caracteristiques9: "Compatibilité : Windows 10 /11 ; MacOS 10.11+",
  },
  
  {
    uuidProduit: "1a289892-7b97-4683-ba46-174e4a4d556f",
    marque: "Logitech",
    modele: "910-006559",
    taille: "84.3 mm x 124.9 mm",
    title: "Un feeling incroyable",
    descriptif1: "Avec la Logitech MX Master 3S, profitez d'une icône remasterisée offrant une précision instantanée et un potentiel infini. Conçue pour offrir précision, contrôle et confort aux utilisateurs expérimentés, la souris sans fil Logitech MX Master 3S se caractérise notamment par une forme parfaitement adaptée à la main, un capteur de 8000 dpi, des fonctionnalités avancées et une conception incroyable.",
    descriptif2 : "La Logitech MX Master 3S embarque la roulette à défilement électromagnétique MagSpeed afin de vous offrir suffisamment de précision et de rapidité pour faire défiler pas moins de 1000 lignes en une seconde. Quasi silencieuse, elle est construite en acier usiné qui lui confère un toucher premium et un poids suffisant pour offrir une inertie dynamique que vous ressentez, mais que vous n'entendez pas ! L'acier usiné de la roulette lui confère une tactilité supérieure et un poids suffisant pour offrir une inertie dynamique que vous sentez mais n'entendez pas.",
    descriptif3: "La Logitech MX Master 3S est équipée de la technologie Logitech Flow. Cette dernière, révolutionnaire, vous permet de déplacer le curseur de votre souris d'un ordinateur à un autre (jusqu'à 3 ordinateurs), d'effectuer des copier-coller de texte, d'une image ou encore d'un fichier d'une machine à une autre. Vous allez ainsi pouvoir transférer vos contenus entre 3 ordinateurs différents sans la moindre difficulté. Plus besoin de transférer vos fichiers sur des clés USB, commencez votre travail sur votre ordinateur portable lors de vos déplacements et finissez-le à la maison sur votre ordinateur de bureau sans faire plusieurs manipulations.",
    caracteristiques1: "Souris optique 1000 dpi",
    caracteristiques2: "Technologie Logitech Flow : vous permet de transférer vos dossiers, images, textes d'un ordinateur à un autre",
    caracteristiques3: "Design ergonomique qui épouse la forme de votre main",
    caracteristiques4: "Roulette de défilement électromagnétique MagSpeed pour une précision et une rapidité incroyable",
    caracteristiques5: "Molette exclusive pour le pouce pour une navigation encore plus fluide",
    caracteristiques6: "Double connectivité : récepteur Logitech Unifying ou technologie Bluetooth Smart",
    caracteristiques7: "Batterie rechargeable avec une autonomie pouvant aller jusqu'à 70 jours",
    caracteristiques8: "Portée de la connexion sans fil : 10 mètres",
    caracteristiques9: "Câble de charge USB-C (USB-A vers USB-C)",
    caracteristiques10: "Compatible Windows 7, 8, 10 et Mac OS X (version 10.10 ou ultérieure)",
    caracteristiques11: "Dimensions : 51 x 84.3 x 124.9 mm",
    caracteristiques12: "Poids : 141 g"
  },{
    uuidProduit: "4b7a5dd7-9019-4638-abe5-8cb41978c2d0",
    marque: "LogitechLogitech",
    modele: "910-002236",
    taille: "39 mm x 60 mm",
    title: "Une souris sans fil prête à l'emploi",
    descriptif1: "Vous recherchez une souris simple, fiable et dotée de la technologie sans fil prête à l'emploi ? Alors la Logitech Wireless Mouse M185 est faite pour vous ! Profitez de la fiabilité d’un dispositif filaire, mais avec la liberté et la commodité de la technologie sans fil : transmission rapide des données et aucune perte de signal. L’autonomie d’un an de la pile permet également de limiter les désagréments liés à cette dernière. Par ailleurs, cette souris confortable et profilée est parfaitement adaptée à la forme de votre main, quant à son installation, pas besoin de logiciel, branchez le nano-récepteur compact sur un port USB de votre PC et vous pouvez vous servir de votre M185 immédiatement. De plus vous pouvez le laisser sur le port USB afin d'éviter tout risque d'égarement.",
    descriptif2 : "La conception incurvée de la Logitech Wireless Mouse M185 convient aux droitiers comme aux gauchers et assure plus de confort qu'un pavé tactile. Sa forme profilée étant parfaitement adaptée à la forme de votre main. Elle est dotée de la technologie sans fil avancée 2.4 GHz de Logitech qui garantit une connexion puissante et fiable, sans aucun délai.",
    descriptif3: "Avec la Logitech Wireless Mouse M185 vous bénéficiez, outre la qualité et la fiabilité supérieures qui font la renomée de Logitech, d'une longévité de la pile allant jusqu'à 12 mois (selon votre utilisation). Ainsi, que vous soyez en déplacement ou à la maison, il vous suffira de brancher le nano-récepteur USB ultra-discret sur votre ordinateur pour utiliser votre souris immédiatement.	",
    caracteristiques1: "Technologie sans fil 2,4 GHz de pointe",
    caracteristiques2: "Forme confortable et incurvée",
    caracteristiques3: "Nano-récepteur USB ultra-discret",
    caracteristiques4: "Compatible Windows Vista, Windows 7, Windows 8 et Windows 10",
    caracteristiques5: "Dimensions récepteur (H x L x Ép) : 14,4 x 18,7 x 6,1 mm",
    caracteristiques6: "Poids récepteur : 1,8 g",
    caracteristiques7: "Dimensions souris (H x L x Ep) : 99 x 60 x 39 mm",
    caracteristiques8: "Poids de la souris (batterie incluse): 75,2 g",
    caracteristiques9: "Type de piles : 1 x AA",
    caracteristiques10: "Autonomie de 1 an",
  },{
    uuidProduit: "a80f4913-8e07-4fd2-8b43-836f0e78a963",
    marque: "Logitech",
    modele: "910-005448",
    taille: "78.5 mm x 79 mm",
    title: "L'ERGONOMIE À SON PAROXYSME",
    descriptif1: "Avec son design né de la science et des performances élevées de la série MX de Logitech, la souris MX Vertical est une souris ergonomique conçue pour offrir précision, contrôle et confort aux utilisateurs expérimentés. Dites adieu à l'inconfort avec cette souris conçue pour améliorer la posture et réduire les contraintes musculaires et la pression exercée sur le poignet. La position naturelle de la main réduit la pression exercée sur le poignet et l'avant-bras. L'angle vertical unique à 57° a été optimisé pour offrir une posture ergonomique sans compromettre les performances.",
    descriptif2 : "La Logitech MX Vertical réduit la tension musculaire de 10% et favorise une posture plus ergonomique pour que vous puissiez travailler sans la moindre gêne. De plus, l'angle vertical unique à 57° réduit la pression exercée sur votre poignet, tandis que votre pouce repose confortablement sur l'emplacement prévu à cet effet. Douce au toucher, la souris MX Vertical est conçue pour s'adapter à la main. Sa forme unique s'adapte parfaitement à de nombreuses formes et tailles de mains et la surface texturée en caoutchouc assure une prise en main naturelle.",
    descriptif3: "La souris MX Vertical a été conçue et testée sur la base de critères élaborés par les meilleurs ergonomes afin d'améliorer la posture, de réduire les contraintes musculaires et la pression exercée sur le poignet. Le suivi optique avancé de 4000 dpi avec commutateur de vitesse de curseur dédié réduit de 4 fois les mouvements de la main, réduisant la fatigue imposée aux muscles du bras et de la main. La vitesse et la précision du curseur peuvent être personnalisées dans logiciel Logitech Options.",
    caracteristiques1: "Souris ergonomique avec position naturelle de votre main et meilleure position du poignet",
    caracteristiques2: "Angle vertical unique de 57°",
    caracteristiques3: "Capteur optique haute précision de 4000 dpi",
    caracteristiques4: "Surface texturée pour une prise en main naturelle",
    caracteristiques5: "Technologie Logitech Flow pour contrôler plusieurs ordinateurs à l'aide d'une souris ou d'un clavier",
    caracteristiques6: "Roulette de défilement premium",
    caracteristiques7: "Autonomie : 4 mois",
    caracteristiques8: "Charge super rapide : 1 minute de charge offre 3 heures d'utilisation",
  },{
    uuidProduit: "fefb2e4d-5f26-4b30-9ff4-0a369b26c574",
    marque: "Logitech",
    modele: "910-006865",
    taille: "97.7 mm x 61.5 mm",
    title: "Profitez du silence",
    descriptif1: "Grâce à la souris Logitech M171 Wireless Mouse, profitez de la fiabilité d'un dispositif filaire, mais avec la liberté et la commodité d'une connexion sans fil d'une portée de 10 mètres grâce à la technologie sans fil 2,4 GHz de pointe Logitech. Abordable et simple d'utilisation, il vous suffit de connecter le nano-récepteur sans fil à un port USB pour utiliser la souris",
    descriptif2 : "La Logitech M171 dispose d'une connexion sans fil fiable à une distance maximale de 10 mètres. Cette dernière dispose d'aucun temps de latence ou de perte de connexion, vous pouvez ainsi travailler en toute confiance. Véritablement prête à l'emploi, il vous suffit d'insérer le nano-récepteur à un port USB de votre ordinateur pour pouvoir l'utiliser. Il n'y a donc pas besoin de coupler la souris ou de télécharger un logiciel.",
    descriptif3: "La forme de la souris Logitech M171 Wireless Mouse épouse la forme de votre main pour des heures d'utilisation tout en confort. La forme ambidextre et la fonction de réassignation des boutons droit et gauche font la souris M171 un produit idéal, que l'on soit gaucher ou droitier.",
    caracteristiques1: "Souris sans fil optique avec connexion 2.4 GHz",
    caracteristiques2: "Portée sans fil : 10 mètres",
    caracteristiques3: "Fonctionne avec 1 pile AA",
    caracteristiques4: "Autonomie : 1 an",
    caracteristiques5: "Compatibilité : Windows 7, Windows 8, Windows 10 et versions ultérieures, Mac OS X 10.8 ou version ultérieure, Chrome OS, Noyau Linux 2.6 ou version ultérieure",
    caracteristiques6: "Dimensions (hauteur x largeur x épaisseur) : 97.7 x 61.5 x 35.2 mm",
    caracteristiques7: "Poids : 70.5 grammes",
  },

  {
    uuidProduit: "d1fc56db-1a0c-4910-ba41-93d6b3b649f8",
    marque: "Acer",
    modele: "UM.QX0EE.H02",
    taille: "540 mm x 414 mm",
    title: "Expérience visuelle Full HD avec couleurs éclatantes",
    descriptif1: "Polyvalent et simple à prendre en main, ce moniteur Acer conviendra aussi bien pour le multimédia que la bureautique ou le jeu. Il est équipé d'une dalle IPS de 23.8 pouces offrant de belles couleurs et un angle de vue de 178°. Visuellement, retrouvez une résolution agréable Full HD ainsi qu'un contraste élevé.",
    descriptif2 : "L'écran KA240YHbi se pare de fonctionnalités gaming pour vous détendre au quotidien. Outre le temps de réponse de 4 ms (gris à gris) ou 1 ms (en mode Visual Response Boost) et un taux de rafraîchissement de 100 Hz, vous bénéficierez d'une belle fluidité grâce à la présence de la technologie AMD FreeSync. Enfin, vos yeux seront parfaitement protégés en l'absence de scintillement et d'une protection de lumière bleue.",
    caracteristiques1: "Écran de 23.8 pouces antireflets avec résolution Full HD (1920 x 1080)",
    caracteristiques2: "Dalle VA : couleurs riches et nuancées avec angles de vision larges",
    caracteristiques3: "Couleurs profondes et nuancées avec contraste dynamique de 100 000 000:1 (standard 3000:1)",
    caracteristiques4: "Performances gaming : 4 ms / 1 ms (VRB), 100 Hz, AMD FreeSync",
    caracteristiques5: "Connecteurs : HDMI 1.4 + VGA",
    caracteristiques6: "Confort oculaire optimal avec les technologies anti-lumière bleue et anti-scintillements",
    caracteristiques7: "Design épuré aux bords fins",
  },{
    uuidProduit: "78c2206e-342d-4968-a53f-4a5881910077",
    marque: "AOC",
    modele: "24G2SPAE/BK",
    taille: "539 mm x 374 mm",
    title: "Vivez un moment de gloire avec AOC",
    descriptif1: "Avec le moniteur gaming AOC 24G2SPAE, vous bénéficiez d'un environnement de jeu pour atteindre les sommets ! Image Full HD sur une dalle IPS de 24 pouces, 165 Hz, 1 ms et Adaptive Sync, toutes les conditions sont réunies pour garantir fluidité, performances visuelles supérieures et confort immédiat. De plus, ce modèle dispose d'une connectique complète et d'une belle protection oculaire.",
    descriptif2 : "L'écran gaming AOC 24G2SPAE accompagne le joueur dans les meilleures conditions. Ce modèle est équipé d'une dalle IPS de 23.8 pouces offrant des couleurs riches, un contraste saisissant et des angles de vision larges. Ce modèle est capable d'afficher une résolution Full HD et est doté d'un design aux bords fins pour un confort supplémentaire lors de vos parties.",
    descriptif3: "Partenaire de jeu efficace, ce moniteur signé AOC offre des performances à la hauteur de vos attentes. Retrouvez ainsi un temps de réponse ultra-rapide de 1 ms (MPRT), un taux de rafraîchissement maximal de 165 Hz ainsi qu'une belle fluidité dans vos parties avec Adaptive Sync.",
    caracteristiques1: "Ecran IPS de 23.8 pouces avec résolution Full HD (1920 x 1080 pixels)",
    caracteristiques2: "Gamut couleurs : 126% sRGB, 94% Adobe RGB, 96% NTSC, 93% DCI-P3",
    caracteristiques3: "Affichage ultra-fluide avec une fréquence d'affichage de 165 Hz",
    caracteristiques4: "Temps de réponse : 1 ms (MPRT) / 4 ms (gris à gris)",
    caracteristiques5: "Adaptive Sync",
    caracteristiques6: "Confort oculaire optimisé avec les technologies Flicker-Free et Low-Blue Light",
    caracteristiques7: "2 connecteurs HDMI 1.4 + 1 connecteur DisplayPort 1.2 + 1 port VGA",
    caracteristiques8: "Design gaming sans bords sur 3 côtés",
    caracteristiques9: "Puissance sonore : 2 x 2 Watts",
  },{
    uuidProduit: "e83f5aeb-d151-4f16-a6de-6a4d5c488f0d",
    marque: "Samsung",
    modele: "LC27G55TQBUXEN",
    taille: "616.6 mm x 477.4 mm",
    title: "Un grand écran avec dalle incurvée 1000R au format 16/9",
    descriptif1: "Partez à la conquête de succès futurs avec l'écran gaming Samsung Odyssey G5 C27G55TQBU ! Offrant des performances élevées, une immersion supérieure et un confort permanent, ce modèle vous assurera des conditions rêvées pour atteindre les sommets dans vos jeux préférés. Parmi ses qualités, profitez d'une dalle VA incurvée (1000R) de 27 pouces avec résolution WQHD, d'une arme redoutable (1 ms, 144 Hz, FreeSync Premium) et d'un design épuré aux bords fins et au look futuriste.",
    descriptif2 : "Avec sa courbure 1000R, le moniteur Odyssey G5 vous plonge au coeur de votre jeu pour une immersion gaming de chaque instant ! Sur une dalle VA de 27 pouces au format 16/9 bénéficiez d'un contraste supérieur et d'une belle richesse des couleurs pour retrouver toute l'ambiance de vos jeux préférés. La résolution WQHD (2560 x 1440) apporte des détails élevés tandis que la prise en charge HDR10 offre un spectacle inoubliable. Le design futuriste du moniteur Samsung Odyssey G5 ne laissera personne indifférent. Il dispose d'un cadre et de bords fins pour servir parfaitement l'immersion visuelle. Côté confort, vos yeux seront préservés grâce à la technologie FlickerFree (anti-scintillement) et au mode Eye Saver (réduction lumière bleue).",
    descriptif3: "Les gamers pourront profiter de conditions optimales grâce à des performances élevées. Ainsi, affrontez vos adversaires en toute sérénité avec un temps de réponse ultra-rapide de 1 ms et une fréquence de rafraîchissement maximale de 144 Hz. En outre, cet écran incurvé gaming intègre AMD FreeSync Premium pour des sessions fluides sans déchirures d'image. Vous avez en plus la possibilité d'activer le mode faible input lag et de profiter de la technologie Black Equalizer pour éclairer les scènes sombres et ne pas vous faire surprendre par l'ennemi !",
    caracteristiques1: "Moniteur LED de 27 pouces avec résolution WQHD (2560 x 1440)",
    caracteristiques2: "Dalle VA incurvée 1000R : immersion supérieure",
    caracteristiques3: "Prise en charge HDR10",
    caracteristiques4: "AMD FreeSync Premium",
    caracteristiques5: "Affichage fluide avec un temps de réponse de 1 ms",
    caracteristiques6: "Taux de rafraîchissement maximal 144 Hz",
    caracteristiques7: "Connecteurs : HDMI 2.0 + DisplayPort 1.2",
    caracteristiques8: "Meilleur confort oculaire avec le mode Eye Saver et la technologie Flicker Free",
  },{
    uuidProduit: "043b79ac-273e-49a3-9273-09c081c9299e",
    marque: "AOC",
    modele: "C27G2ZE/BK",
    taille: "612.37 mm x 398.6 mm",
    title: "La gloire est toute proche avec AOC",
    descriptif1: "Préparez-vous pour les échéances à venir en intégrant dans votre arsenal le moniteur AOC C27G2ZE ! Ce modèle incurvé 240 Hz à dalle VA de 27 pouces possède toutes les qualités pour vous mener directement vers la victoire. Bénéficiez d'un temps de réponse ultra-rapide, appréciez le travail de la technologie AMD FreeSync Premium et mettez toutes les chances de votre côté pour surpasser vos adversaires.",
    descriptif2 : "Vivez une expérience gaming en totale immersion avec le moniteur AOC C27G2ZE et sa dalle VA incurvée de 27 pouces ! Profitez d'une résolution Full HD, de couleurs naturelles et d'angles de vision larges pour jouer dans les meilleures conditions. Une belle luminosité de 300 cd/m² ainsi qu'un contraste dynamique de 80M:1 sont au rendez-vous pour vous faire vivre des moments intenses à chaque partie.",
    descriptif3: "Côté performances, ce modèle dispose d'un temps de réponse de 0.5 ms (MPRT), d'une fréquence de rafraîchissement maximale de 240 Hz et de la technologie AMD FreeSync Premium avec fonction LFC. Cette dernière supprime le risque de saccade si la fréquence d'image passe sous la fréquence de rafraîchissement. Et pour s'intégrer parfaitement dans votre environnement gaming, le moniteur incurvé C27G2ZE possède deux ports HDMI et un connecteur DisplayPort. Enfin, le confort oculaire est également disponible avec les bienfaits des technologies FlickerFree et Low Blue Light.",
    caracteristiques1: "Moniteur incurvé (1500R) de 27 pouces avec résolution Full HD (1920 x 1080 pixels)",
    caracteristiques2: "Dalle VA : couleurs superbes et angles de vision larges (178°)",
    caracteristiques3: "Taux de rafraîchissement maximal de 240 Hz",
    caracteristiques4: "Affichage fluide avec un temps de réponse de 0.5 ms (MPRT)",
    caracteristiques5: "Technologie AMD FreeSync Premium avec fonction LFC",
    caracteristiques6: "Bonne richesse de couleurs avec un contraste dynamique de 80 000 000:1 (typique 3000:1)",
    caracteristiques7: "Connecteurs numériques HDMI et DisplayPort",
    caracteristiques8: "Design borderless sur 3 côtés",
    caracteristiques9: "Confort oculaire : technologie Flicker Free (anti-scintillement) et mode Low Blue Light (réduction de la lumière bleue)",
    caracteristiques10: "Garantie constructeur 3 ans",
  },
  
  {
    uuidProduit: "a2542a0d-cfb8-41d8-9ae8-9e6a15607d1e",
    marque: "ASRock",
    modele: "RX6600 CHALLENGER D 8G",
    taille: "269 mm x 132 mm",
    title: "Architecture AMD RDNA 2 et ray tracing matériel",
    descriptif1: "Basée sur l'architecture AMD RDNA 2 et prenant en charge le ray tracing, la carte graphique ASRock AMD Radeon RX 6600 Challenger D 8GB vous propose de jouer dans les meilleures conditions avec des graphismes sublimes et une fluidité remarquable. C'est la carte graphique idéale pour jouer en Full HD. Avec 1792 processeurs de flux, des fréquences élevées et 8 Go de VRAM GDDR6, la carte graphique gaming AMD Radeon RX 6600 est conçue pour profiter au mieux des meilleurs Jeux PC, tout simplement.",
    descriptif2 : "AMD RADEON RX 6600 CHALLENGER D 8GB Design Dual-Fan à 2 ventilateurs Backplate métal Ventilateurs Striped Axial Fan Fonction 0dB Silent Cooling lorsque la carte est peu sollicitée Heatpipes cuivre avec zone de contact améliorée Dissipateur aluminium à ailettes fines haute densité Compatible avec le logiciel ASRock Tweak 2.0",
    descriptif3: "TECHNOLOGIES DE POINTE POUR LE JEU Accédez à la meilleure expérience de gaming avec de nouvelles fonctionnalités, de nouveaux niveaux d’efficacité réactive et un écosystème de gaming vraiment avancé. Les cartes graphiques AMD Radeon RX série 6000 améliorent votre expérience gaming.  Ray tracing matériel FidelityFX Contrast / HDR FreeSync Premium DirectX 12 Ultimate",
    caracteristiques1: "GPU: 1",
    caracteristiques2: "RAM: 8Go",
    caracteristiques3: "Fréquence mémoire vidéo: 14000 MHz",
    caracteristiques4: "Fréquence mémoire vidéo: 14000 MHz",
    caracteristiques5: "Type de mémoire: GDDR6",
  },{
    uuidProduit: "6e28986b-5983-4321-b3ec-aa2d940ad221",
    marque: "ASRock",
    modele: "RX7900XTX TCW 24GO",
    taille: "345 mm x 140 mm",
    title: "Le Jeu en 4K UHD et plus encore ",
    descriptif1: "Basée sur l'architecture RDNA 3, la carte graphique ASRock AMD Radeon RX 7900 XTX Taichi White 24GB OC est conçue pour le Jeu en 4K UHD. Puissante et efficace, elle ravira joueurs et créatifs à la recherche d'une solution graphique performante et novatrice. Les technologies de pointe comme AMD Radeon Super Resolution, AMD Smart Access Memory, AMD Radeon Boost, AMD FreeSync ou encore AMD Radeon Anti-Lag vous permettent d'obtenir des jeux ultra-fluides avec un rendu graphique spectaculaire.",
    descriptif2 : "La carte graphique AMD Radeon RX 7900 XTX est propulsée par l’architecture AMD RDNA 3. Elle est dotée de 96 unités de calcul améliorées, du nouvel AMD Infinity Cache de 96 Mo et de 24 Go de mémoire dédiée GDDR6. Elle est conçue pour offrir des fréquences d'images ultra-élevées et une impressionnante résolution de gaming 4K en toute fluidité.",
    descriptif3: "La Taichi White OC propose un système de ventilation à trois ventilateurs pour un refroidissement optimal pendant vos sessions de gaming et dispose d'un mode 0dB lorsque la carte est peu sollicitée.",
    caracteristiques1: "96 Unités de calcul",
    caracteristiques2: "96 Ray Accelerators",
    caracteristiques3: "192 ROP",
    caracteristiques4: "6144 Processeurs de flux",
    caracteristiques5: "6 Shader Engines",
  },{
    uuidProduit: "d3684f5a-3e62-49c5-9f82-52c3a9384da8",
    marque: "ASUS",
    modele: "DUAL-RX7700XT-O12G",
    taille: "279.9 mm x 1339.9 mm",
    title: "Jouez et Streamez en 1440p ",
    descriptif1: "L'architecture RDNA 3 d'AMD vous propulse dans le monde du jeu vidéo de manière unique et spectaculaire avec la carte graphique ASUS Dual Radeon RX 7700 XT O12G. Parfaite pour le jeu en 1440p et capable d'offrir de bonnes performances en 4K, la carte graphique AMD Radeon RX 7700 XT vous permet également de jouer et de streamer en même temps. Le ray tracing, l'accélération par IA et les technologies avancées d'AMD vous permettent d'obtenir des jeux ultra-fluides avec un rendu graphique exceptionnel.",
    descriptif2 : "L'ASUS Dual Radeon RX 7700 XT OC Edition 12GB GDDR6 cumule durabilité, compatibilité et performances pour apporter satisfaction aux gamers les plus exigeants. Les fonctionnalités de cette carte graphique incluent des technologies de pointe ainsi qu'un système de refroidissement exclusif à la marque ultra-efficace.",
    caracteristiques1: "216 Unités de texture",
    caracteristiques2: "54 Unités de calcul",
    caracteristiques3: "54 Ray Accelerators",
    caracteristiques4: "108 AI Accelerators",
    caracteristiques5: "96 ROP",
    caracteristiques6: "3456 Processeurs de flux",
  },{
    uuidProduit: "f0b151f1-4ef2-426a-8c6f-97dd2edfc43d",
    marque: "ASUS",
    modele: "90YV0AG7-M0NA00",
    taille: "192 mm x 115 mm",
    title: "AMD Radeon RX 550 : Une carte référence pour les \"casual Gamer\"",
    descriptif1: "La carte graphique Asus PH-RX550-4G-EVO est idéale pour les jeux en ligne (League of Legends, Overwatch, Rocket League, Counter Strike ...) et les \"casual gamers\" à la recherche d'une solution \"Gaming\" abordable et efficace. Elle vous permettra de profiter des derniers Hits PC de manière fluide. Grâce aux utilitaires Radeon, vous pilotez littéralement votre carte, vous maitrisez votre matériel pour obtenir des résultats prodigieux ! Et pour les amateurs de multimédia, la carte prend en charge les vidéos 4K avec encodage H.265 ansi que les résolutions d'affichage jusqu'à 3840×2160 pixels.",
    descriptif2 : "Les cartes graphiques Radeon RX 500 ciblent les gamers qui souhaitent bénéficier de performances exceptionnelles au juste prix. Pour les gamers qui veulent la flexibilité sans compromis.",
    descriptif3: "Reprenez les commandes avec une interface intuitive et un overclocking amélioré (selon les modèles). Découvrez les exceptionnelles performances des shaders asynchrones, de DirectX 12, Vulkan et FreeSync, la technologie ouverte d'AMD, et profitez d'une remarquable fluidité et de fréquences d'images élevées sans déchirement de l'écran ou temps de latence.",
    caracteristiques1: "Conçu pour les titres eSports",
    caracteristiques2: "Prise en charge DirectX 12",
    caracteristiques3: "FreeSync 2 et gaming HDR",
    caracteristiques4: "Overclockée: Oui",
  }
  ]
}
